### ISSUE TITLE
Text doesn't clear after successful entry

### ISSUE THREAD

**Issue by edwinfinch** [vgmoose/tertiary_text#6]
I am integrating tertiary text into my app. First off, thanks for an awesome typing mechanism and allowing other developers to integrate it.

My problem is, after entering text, the text on tertiary text does not clear. I have tried a few methods to clear it myself; such as running a for loop to clear all places, but this only causes a weird bug where it puts a space in between all entries. I've tried clearing the text_buffer completely, but then this results in not being able to type at all.

How can I fix this issue?
Thanks

**Comment by vgmoose** [comment]
Hi!

I have just made a commit https://github.com/vgmoose/tertiary_text/commit/be539a40a841563098a31b5342b9c676187641ea that should address this issue. The code I used to clear it is as follows.

```C
    for (int i=0; i<MAX_CHARS; i++)
        text_buffer[i] = '\0';
    pos = 0;
}
```

Keep in mind that the text_buffer is the same pointer that is being passed to the callback, so if you need the string to persist through a second invocation of the tertiary text dialog, the string will need to be copied.

Let me know if the fix works. Thank you!

**Comment by edwinfinch** [comment]
This works great, thanks a lot. I had been copying my strings already, but thanks for looking out for that!

Anyway, I've been writing Pebble apps for over a year and have a lot of experience in C. If I were to rewrite Tertiary Text, would you apply those changes do you think? Or is it not worth my time?

**Comment by vgmoose** [comment]
Yes absolutely! Tertiary Text really needs some love from someone who has a deeper understanding of Pebble and C. Even diving into it now to make that fix, I am aware that the source code / API is a little wonky, and there are probably cleaner ways to go about it.

Don't feel like you have to, but if you have changes to make that would improve it, I would certainly apply them.

**Comment by edwinfinch** [comment]
That's awesome. I'd love to rewrite it and maybe add some new features. I'll probably make a rewrite pull request within a week or two.
